
version: 2.1

orbs: 
  codecov: codecov/codecov@3.2.2
  node: circleci/node@4.7.0
workflows:
  upload-to-codecov:
    jobs: 
        - node/test: 
            post-steps: 
              - codecov/upload:
                file: './coverage/clover.xml'
                token: 7025d4e8-9bf4-402a-b21d-79d4abb7848e
  
