
version: 2.1

orbs: 
  codecov: codecov/codecov@3.2.2
  node: circleci/node@4.7.0

jobs:
  say-hello:
    
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  upload-to-codecov:
    jobs: 
        - node/test: 
            post-steps: 
              - codecov/upload:
                file: './coverage/clover.xml'
                token: bc2e56b0-7dfa-4d51-b660-a5ad1525deca
  say-hello-workflow:
    jobs:
      - say-hello
