# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2
  node: circleci/node@4.7
Run-With-Node:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: install and run tests
          command: |
            yarn install && yarn test
      - codecov/upload:
          file: './coverage/clover.xml'
          token: 7025d4e8-9bf4-402a-b21d-79d4abb7848e
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload

  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      run_test:
        docker: 
          -image: circleci/node: 16.14.2
        steps:
          -checkout
          -run: node --version
      - node/test:
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
          version: "16.10"
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: npm

- name: Codecov
  uses: codecov/codecov-action@v3.0.0
